gateways:
    big_query:
        connection:
            type: bigquery
            method: service-account
            keyfile: ../secret/gcp_secret.json
            project: terraform-demo-412002       
        state_connection:
            type: duckdb
            database: db.db

default_gateway: big_query

model_defaults:
    dialect: bigquery
